### ISSUE TITLE
map location picker + backend

### ISSUE THREAD

**Issue by mikeyliang** [mikeyliang/clubspace#18]
frontend picker + backend meeting location update. dependent on #17 

- [ ] update schema & prisma as needed
- [ ] add new fields to store map info
- [ ] create new service controller model to update and create new map info
- [ ] add on frontend a marker of meeting location 
- [ ] ensures code works with resolved #17

**Comment by mikeyliang** [comment]
- [ ] update schema & prisma as needed
- [ ] add new fields to store map info
- [ ] create new service controller model to update and create new map info
- [ ] add on frontend a marker of meeting location 
- [ ] ensures code works with resolved #17

**Comment by brandonysli** [comment]
overdue
