### ISSUE TITLE
week 1 prereqs

### ISSUE THREAD

**Issue by brandonysli** [mikeyliang/clubspace#31]
must complete before april 22th meeting
**end goal: display aerial robotics page below on browser (localhost)**
[
<img width="1824" alt="image" src="https://user-images.githubusercontent.com/115840552/231961759-41ee3d94-7f2c-479c-9b1d-263d8bbad0e6.png">
](url)

tasks:
- set up PostgreSQL (https://postgresapp.com/), install tableplus and postman
- pull from main/create new branch/install dependencies
- create env file and link local database to project
- connect to database inside database management app (e.g TablePlus)
- seed data from project to database (look for files that seed and then scripts inside package.json)
- play around with tableplus, use postman to send requests 
- ^ get all clubs and attempt to get all clubs and an individual club by id
-  try to also create a new club based on the schema requirements using postman
- draw on paper a diagram depicting a model of front-end and back-end with references to database/browser/server
- look at frontend code and do some research on web routes. How do you get the above picture to show up (hint: look at the webpage url)
- complete end goal

**Comment by mikeyliang** [comment]
make sure to pull first
